add copy constructor support to Vxy and Vxyz, add from_list() method …
sandialabs/OpenCSP pull request #147
Opened 2024-08-06 04:05 UTC by bbean23

- add copy constructor support to Vxy and Vxyz
- add from_list() method to Vxy and Vxyz
- add asindex() method to Vxy

2024-08-06 21:57 UTC, e10harvey requested changes
Please add docstring for public members. If it would take 30 minutes or less work to add unit tests, please do so.

2024-08-06 21:57 UTC, e10harvey commented on opencsp/common/lib/geometry/Vxy.py
> +    def from_list(cls, vals: list["Vxy"]):
Docstring

2024-08-07 18:53 UTC, bbean23 commented on opencsp/common/lib/geometry/Vxy.py
> +    def from_list(cls, vals: list["Vxy"]):
Done! Also added unit tests.

2024-08-07 21:31 UTC, e10harvey approved these changes

2024-08-07 21:31 UTC, merged