160 clean up abstractspotanalysisimageprocessor
sandialabs/OpenCSP pull request #162
Opened 2024-08-20 01:46 UTC by bbean23

This PR is a biggie. It includes:

* combining AbstractSpotAnalysisImageProcessor and it's ...Leger class
* moving much of the cacheing logic to CacheableImage
* adding lots of tests
* code cleanup and documentation

2024-10-31 15:28 UTC, rcbrost commented
Randy Brost started reviewing this on Thursday October 31 at 9:27 AM.

2024-10-31 16:02 UTC, e10harvey requested changes
Thank you for these changes, @bbean23. Most of my comments are related to the end-user documentation. However, I think given the nature of these changes, it makes sense to share before and after performance metrics. Is there a example or test you could run to share memory usage and runtime before & after these changes?

2024-10-31 16:02 UTC, e10harvey commented on opencsp/common/lib/cv/test/test_CacheableImage.py
> +        """Verify that after saving the image, cacheing no longer creates a cache file"""
Should this (and can it) check whether the in-memory np array & image are 0 bytes?

2024-11-06 20:43 UTC, bbean23 reviewed
I believe I've addressed all your comments. Please approve when ready.

2024-11-06 20:43 UTC, bbean23 commented on opencsp/common/lib/cv/CacheableImage.py
> +        if total_mem_size <= memory_limit_bytes:
I disagree. By providing the `memory_limit_bytes` as a parameter, we're effectively enabling the user to choose a lower memory threshold than is the default. There's also the benefit of requiring the user to think about how much memory they want to use, which is going to be system and application specific.

2024-11-06 20:43 UTC, bbean23 commented on opencsp/common/lib/cv/CacheableImage.py
> +        if total_mem_size <= memory_limit_bytes:
added this same comment to the code

2024-11-06 20:43 UTC, bbean23 commented on opencsp/common/lib/cv/CacheableImage.py
> +        strings) as necessary in order to reduce memory usage."""
done

2024-11-06 20:43 UTC, bbean23 commented on opencsp/common/lib/cv/CacheableImage.py
> +        the newly given path.
Actually, going back in and expanding the documentation on this saved me from a potential bug! Thanks!

2024-11-06 20:43 UTC, bbean23 commented on opencsp/common/lib/cv/CacheableImage.py
> +        elif ft.file_exists(self.cache_path) and os.path.getsize(self.cache_path) > 10:
done! (the answer is paranoia)

2024-11-06 20:43 UTC, bbean23 commented on opencsp/common/lib/cv/CacheableImage.py
> +            enforce_source_image_matches = True
done

2024-11-11 16:11 UTC, e10harvey approved these changes

2024-11-11 16:12 UTC, merged