added SystemSofastFixed
sandialabs/OpenCSP pull request #78
Opened 2024-04-10 18:48 UTC by braden6521

- Renamed old SystemSofastFixed to PatternSofastFixed (analog of SofastFringe `Fringes.py` class)
- Created new SystemSofastFixed (analog of SystemSofastFringe)
- Pulled all of these together into a Sofast command line interface (/contrib/app/sofast/)

2024-04-15 22:19 UTC, bbean23 requested changes
Again, I have just a few comments. Please address them and I'll approve.

2024-04-15 22:19 UTC, bbean23 commented on opencsp/app/sofast/test/ImageAcquisition_no_camera.py
> +        time.sleep(self._shutter / 1e6)
Huh, didn't realize this wasn't here. Nifty!

2024-04-17 20:16 UTC, braden6521 commented on opencsp/app/sofast/lib/SystemSofastFixed.py
> +        Instantiates SystemSofastFringe class.
Fixed.

2024-04-17 20:16 UTC, braden6521 commented on contrib/app/sofast/sofast_command_line_interface.py
> +    fringes = Fringes(periods_x, periods_y)
Nice; changed!

2024-04-17 20:17 UTC, braden6521 commented on contrib/app/sofast/sofast_command_line_interface.py
> +    lt.logger(join(dir_log, f'log_{_timestamp():s}.txt'), lt.log.INFO)
Done.

2024-04-17 20:17 UTC, braden6521 commented on contrib/app/sofast/sofast_command_line_interface.py
> +    dir_save = abspath(join(dirname(__file__), '../../../../sofast_cli'))
All inputs are now parameterized.

2024-04-17 20:23 UTC, braden6521 commented
@bbean23, thanks for comments! I believed I have addressed them all.

2024-04-17 21:14 UTC, bbean23 approved these changes
Looks good. Approved!

2024-04-17 21:50 UTC, merged