16 making testmotionbasedcantingpy pass
sandialabs/OpenCSP pull request #84
Opened 2024-04-15 22:05 UTC by mhhwang1

Adds TstMotionBasedCanting to determine the azimuth and elevation angles required to hit a target on the top of the towers. 
Includes changes to files (heliostat, solarfield, and facet) to make it run, along with new tower files to render a tower for target location.

Need to add unit tests to server, waiting on future changes to facet class. Will later edit TstMotionBasedCanting to also compute canting angles of heliostat.

2024-04-15 23:42 UTC, bbean23 requested changes
1. There's a number of changes here that I'd like for you address before I approve.
2. Please update the code and tests so that all the CI automation passes.
3. I hope the tests work, because I didn't really read much of the test files. 🤫
4. I suggest adding a few simple tests for planes_line_intersection.py/IntersectionBinarySearch.py

2024-04-15 23:42 UTC, bbean23 commented on opencsp/common/lib/geometry/IntersectionBinarySearch.py
> +        print("Rotating.")
Add this to the proceeding commented-out code instead of logging a statement that isn't true.

2024-04-15 23:42 UTC, bbean23 commented on opencsp/common/lib/geometry/IntersectionBinarySearch.py
> +    # filter out points that miss the plane
Is any filtering being done? If not, can we remove this block of code?

2024-04-15 23:42 UTC, bbean23 commented on opencsp/common/lib/geometry/IntersectionBinarySearch.py
> +def plane_intersec_vec_maddie(
Actually, looking at the code more, does this do a binary search? If not, then how about just "plane_lines_intersection"?

2024-04-15 23:42 UTC, bbean23 commented on opencsp/common/lib/geometry/IntersectionBinarySearch.py
> +def plane_intersec_vec_maddie(
I also suggest adding adding some unit tests for this function in the file `opencsp/common/lib/geometry/test/test_planes_line_intersection.py`. For example:

```python
class test_planes_line_intersection(unittest.TestCase):
    def test_bad_params_raises_error(self):
        """Make sure that passing in bad parameters causes an exception"""
        # too many values for plane
        lines_points = Pxyz([0, 0, 0])
        lines_vecs = Vxyz([0, 0, 0])
        plane_point = Pxyz(np.array([[0, 0], [0, 0], [0, 0]]))
        plane_normal = Pxyz(np.array([[0, 0], [0, 0], [0, 0]]))
        with self.assertRaises(ValueError):
            planes_line_intersection((lines_points, lines_vecs), (plane_point, plane_normal))

        # unmatched dimensions for plane
        with self.assertRaises(ValueError):
            planes_line_intersection((lines_points, lines_vecs), (Pxyz([0, 0, 0]), plane_normal))
        with self.assertRaises(ValueError):
            planes_line_intersection((lines_points, lines_vecs), (plane_point, Pxyz([0, 0, 0])))

        # unmatched dimensions for lines
        with self.assertRaises(ValueError):
            planes_line_intersection((Pxyz(np.array([[0, 0], [0, 0], [0, 0]])),
                                     lines_vecs), (plane_point, plane_normal))
        with self.assertRaises(ValueError):
            planes_line_intersection(
                (lines_points, Pxyz(np.array([[0, 0], [0, 0], [0, 0]]))), (plane_point, plane_normal))

    def test_parallel_line_plane(self):
        """Raise an exception when the line and the plane are parallel"""
        raise NotImplementedError  # TODO

    def test_parallel_coincident_line_plane(self):
        """Raise an exception when the line and the plane are parallel, including the coincident edge case."""
        raise NotImplementedError  # TODO

    def test_x_plane(self):
        """Verify that we can find intersections for a plane with a normal == x-axis"""
        raise NotImplementedError  # TODO

    def test_y_plane(self):
        """Verify that we can find intersections for a plane with a normal == y-axis"""
        raise NotImplementedError  # TODO

    def test_z_plane(self):
        """Verify that we can find intersections for a plane with a normal == z-axis"""
        raise NotImplementedError  # TODO

    def test_multiple_lines(self):
        """Test with two lines and with three lines. We should get the same number of intersection points as the number of lines."""
        raise NotImplementedError  # TODO
        # ...
        self.assertEqual(2, intersection_points.data.shape[1])
```

2024-04-24 18:01 UTC, mhhwang1 commented on opencsp/common/lib/csp/SolarField.py
> +        self.set_position_in_space()
No, they'll be updated when Tristan pushes his edits to the Heliostat and Facet classes, but for now, with the different origins defined in the Facet and Heliostat classes, the translation doesn't make sense in SolarField.

2024-04-24 19:28 UTC, mhhwang1 commented on opencsp/common/lib/geometry/IntersectionBinarySearch.py
> +    # algorithm explained at \opencsp\doc\IntersectionWithPlaneAlgorithm.pdf
I found the PDF, is there a particular location I should upload it to?

2024-06-13 23:31 UTC, e10harvey approved these changes

2024-06-13 23:32 UTC, merged